### ISSUE TITLE
Error in Linkedin Social Icon on Sidebar

### ISSUE THREAD

**Issue by amitness** [girisagar46/girisagar46.github.io#1]
There is an error in the link for the linkedin social icon on the sidebar. 

Add http to the url in this [line](https://github.com/girisagar46/girisagar46.github.io/blob/source/pelicanconf.py#L50) of the ```pelicanconf.py``` to fix it.

**Comment by amitness** [comment]
Btw, your repo caught my eye as it was similar to the source code for my [blog](https://github.com/studenton/studenton.github.io).

**Comment by girisagar46** [comment]
Thanks for pointing out the error. It's been fixed.

It's similar in terms of the configuration source code because I've been playing around with Pelican since few days and your repo and [pythonnepal.github.io](https://github.com/PythonNepal/pythonnepal.github.io) repo has been a great help to understand the configuration.

**Comment by amitness** [comment]
@girisagar46 It's always good to know that your work helped someone. Your take on the code base has taught me few tricks here and there. The reason I love open source. Win win for both :)
